### ISSUE TITLE
URI for CD Groups

### ISSUE THREAD

**Issue by davidcarlisle** [OpenMath/OpenMath.github.io#38]
This is related to issue #16 but a bit different.  The OM standard includes a sample (mathml) CD Group in the appendix 

https://openmath.github.io/standard/om20-2017-07-22/omstd20.html#mathml.cdg

and that claims to have canonical URI of

http://www.openmath.org/cdfiles/cdgroups/mathml.cdg

which works now but will break once openmath,org is served from gh-pages. It doesn't link-check as it's just displayed as verbatim text not as a link in the html.

`/cdfiles/` and the later `/cdfiles2/` areas were the old build areas analogous to the `CDs` repository in the new setup, but the apache server was configured to redirect them both to the top level so the above is the same as

http://www.openmath.org/cdgroups/mathml.cdg

with gh-pages we can add redirects to html (and markdown) pages by adding a `<meta` element to the head but I don't think we can redirect the `cdg` files themselves.

I'd suggest (if @pdfion and @JamesHDavenport agree) that at least the editors draft of that appendix 
change to use http://www.openmath.org/cdgroups/mathml.cdg and that we change all the actual
files not to use `/cdfiles/`  in URL.

For the sake of old links I'd check in (just) http://www.openmath.org/cdfiles/cdgroups/mathml.cdg at exactly that address but wouldn't try to make the build system update `/cdfiles/cdgroups`, just `/cdgroups`

Unrelated to the URL but the text of the mathml cdgroup file in the appendix in the standard is newer and more reasonable than the text in the `.cdg` file (which has a description from me relating to a "core" Cd group that in the end we decided never to make)

**Comment by JamesHDavenport** [comment]
Makes sense. Since it's only an appendix and we're just debugging a link in an example, I'm even inclined to fix the 2.0r1: @pdfion what do you think?

**Comment by davidcarlisle** [comment]
I think we should update the file and spec to use the "new" URL but I have worked out how to redirect on github so

https://openmath.github.io/cdfiles/cdgroups/mathml.cdg

now gives

https://openmath.github.io/cdgroups/mathml

The trick is that 

https://openmath.github.io/cdfiles/cdgroups/mathml.cdg
will serve 
https://openmath.github.io/cdfiles/cdgroups/mathml.cdg.html
if the html file is there and the .cdg file is not there.

The html can be a simple html file using a 
<meta http refresh to redirect to 
/cdgroups/mathml

so (just) this redirect is now checked in as 892128b

**Comment by JamesHDavenport** [comment]
I suspect the file was copied over manually, but the problem is that the base file at
http://www.openmath.org/cdgroups/mathml.cdg
has the /cdfiles in its path. I was going just to take a fresh copy of that file, but it won’t help.
I’ve been at other conferences and rather lost track of OpenMath, but was intending to pick that up again.
I probably ought to have a blitz on pending issues: what’s the correct place for me to clone and make these CD/CDgroup edits from? I hope I have write access to the repository. I think I’d rather do this sort of global edit at work, but that’s just my challenge.
      James

**Comment by davidcarlisle** [comment]
On 14 August 2017 at 07:44, James Davenport <notifications@github.com>
wrote:

> I suspect the file was copied over manually, but the problem is that the
> base file at
> http://www.openmath.org/cdgroups/mathml.cdg
> has the /cdfiles in its path.



Yes I just pinged you as CD/openmath-spec editor for that:-)

The files are mostly in the CDs repository so clone

https://github.com/OpenMath/CDs

but mathml.cdg is also copied into the spec directory

https://github.com/OpenMath/OMSTD

which for historical reasons needs to be a copy (or I could change the spec
build script to fetch a copy from the CDs github?....)

If you push in CDs  repo then travis will update the one on the website.

David

**Comment by JamesHDavenport** [comment]
1) I haven't seen a ping as CD-editor.
2) nevertheless I believe I've updated all CDGs to take out /cdfiles terms. Power of sed and bash loops. But can you check?
3) once this is confirmed, I'll put a copy in the OMSTD directory and let Travis do his thing. I think I'd prefer it if the OMSTD contained copies, so that changes were deliberate.
James

Sent from my iPhone

On 14 Aug 2017, at 08:27, "David Carlisle" <notifications@github.com<mailto:notifications@github.com>> wrote:

On 14 August 2017 at 07:44, James Davenport <notifications@github.com<mailto:notifications@github.com>>
wrote:

> I suspect the file was copied over manually, but the problem is that the
> base file at
> http://www.openmath.org/cdgroups/mathml.cdg
> has the /cdfiles in its path.



Yes I just pinged you as CD/openmath-spec editor for that:-)

The files are mostly in the CDs repository so clone

https://github.com/OpenMath/CDs

but mathml.cdg is also copied into the spec directory

https://github.com/OpenMath/OMSTD

which for historical reasons needs to be a copy (or I could change the spec
build script to fetch a copy from the CDs github?....)

If you push in CDs repo then travis will update the one on the website.

David

**Comment by davidcarlisle** [comment]
On 14 August 2017 at 10:48, James Davenport <notifications@github.com>
wrote:

> 1) I haven't seen a ping as CD-editor.
> 2) nevertheless I believe I've updated all CDGs to take out /cdfiles
> terms. Power of sed and bash loops. But can you check?
>

did you push? I see no changes in OpenMath/Cds ? last commit here was three
days ago

https://github.com/OpenMath/CDs


3) once this is confirmed, I'll put a copy in the OMSTD directory and let
> Travis do his thing. I think I'd prefer it if the OMSTD contained copies,
> so that changes were deliberate.
> James
>
> Sent from my iPhone
>
> On 14 Aug 2017, at 08:27, "David Carlisle" <notifications@github.com<

**Comment by JamesHDavenport** [comment]
Looked like push stalled. Now kicked.
James

**Comment by kohlhase** [comment]
So is this fixed? Can we close?
