### ISSUE TITLE
preserve all the URIs from the old home page.

### ISSUE THREAD

**Issue by kohlhase** [OpenMath/OpenMath.github.io#8]
There may be deep links.

**Comment by kohlhase** [comment]
If we are not able to do that, we should have a really helpful 404.html

**Comment by davidcarlisle** [comment]
we can add redirect pages for each affected URL (these are client redirects not server style but they work OK and it's all gh-pages offers)  see the redirects for all the xhtml links to cds `./cd/quant1.xhtml`    and the redirect for (just) `./cdfiles/cdgroups/mathml.cdg.html`  as there are no server level redirects of whole directories redirecting (say) all the files previously reachable under /cdfiles  would be possible but tedious (just write generate a redirecting stub for every file)  I suggest we don't do them all but just do it for ones where we know there would otherwise be a broken link (eg the mathml spec linked to the .xhtml CD versions, and to cdfiles/cdgroups/mathml.cdg)

**Comment by kohlhase** [comment]
yes, that would be good. Could  you please do this?

**Comment by davidcarlisle** [comment]
Given a list of broken links I could make a script to make the redirect files, but making the input would be easier after the DNS is switched as then we can run some link checkers over this site and for example over the mathml area at w3c and add any redirects needed.

**Comment by kohlhase** [comment]
that is a very pragmatic way of doing this. 
But we should probably check that the main pages (i.e. the links on the front page of the old OpenMath.org still work on the new site). In case someone links deeply.

**Comment by davidcarlisle** [comment]
OK I checked each of the links in the old head and foot banner lines at openmath.org, most of the pages work at the same location at the new site except for the links below, where I have also suggested redirect targets, not an exact match in all cases....


https://www.openmath.org/overview/index.html
-> https://openmath.github.io/about

https://openmath.github.io/lists/index.html
-> https://openmath.github.io/follow


https://openmath.github.io/links/index.html
-> ? https://openmath.github.io/projects


https://www.openmath.org/infrastructure/
-> ?? https://github.com/OpenMath/OpenMath.github.io

**Comment by davidcarlisle** [comment]
These links now all work, redirecting as in the previous comment



https://openmath.github.io/overview/index.html
https://openmath.github.io/overview


https://openmath.github.io/lists/index.html
https://openmath.github.io/lists

https://openmath.github.io/links/index.html
https://openmath.github.io/links


https://openmath.github.io/infrastructure/index.html
https://openmath.github.io/infrastructure

**Comment by kohlhase** [comment]
excellent. I consider this done then.
